version: '3'
services:
  web:
    image: "ruimo/store2"
    ports:
     - "9000:9000"
    volumes:
     - /var/applog:/logs
     - /var/pictures:/var/pictures
    environment:
     - APP_SECRET
     - CONF_FILE
  postgres:
    image: ruimo/df-ub1604-pgsql96x
    volumes:
     - /var/pg_db:/var/pgsql
     - /etc/localtime:/etc/localtime:ro
